name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: public/web
        run: npm install

      - name: Build Angular
        working-directory: public/web
        run: npm run build -- --configuration production --base-href "/Botiquin/"

      - name: Detect build folder
        working-directory: public/web
        run: ls -R dist

      - name: Upload artifact (Angular build)
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/web/dist/Botiquin/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4